<?php
/**
 * Created by PhpStorm.
 * User: Webhouse
 * Date: 9/6/2018
 * Time: 6:50 PM
 */

namespace Modules\Showcase\Products\Controllers;

class ControllerBase extends \Lib\Mvc\Controller
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

}



